---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by justh.
--- DateTime: 25-Sep-22 2:14 AM
---

zalchemyAction = {}

zalchemyAction.ASSIGN = "="
zalchemyAction.ADD = "+="
zalchemyAction.SUBTRACT = "-="
zalchemyAction.MULTIPLY = "*="
zalchemyAction.DIVIDE = "/="
zalchemyAction.PERCENT = "%="
zalchemyAction.APPEND = "&="
zalchemyAction.REMOVE = "^="
zalchemyAction.MIN = "<="
zalchemyAction.MAX = ">="
zalchemyAction.DELETE_PREFIX = "-"
zalchemyAction.CREATE_PREFIX = "+"
zalchemyAction.MULTIPLE_ACTION_SEPARATOR = " "

function zalchemyAction:parse()

end

function zalchemyAction:validate()
  return true
end

function zalchemyAction:validatenumeric(stringToValidate)
  return true
end

function zalchemyAction:new(actionText)
  local o = {}
  setmetatable(o, self)
  self.__index = self
  o.actionText = actionText
  o.is_parsed = false
  o.is_valid = nil
  return o
end