---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by justh.
--- DateTime: 24-Sep-22 6:43 PM
---

local function zalchemy_OnGameStart()
    writeLog("ZALCH","zalchemy OnGameStart event handler called")
end

Events.OnGameStart.Add(zalchemy_OnGameStart);
